### ISSUE TITLE
Playbook requires non standard hash_behaviour

### ISSUE THREAD

**Issue by benwaine** [hoborglabs/ansible_gocd_server#3]
When attempting to follow the example in the README an error is thrown indicating that not all parameters of the `goserver` dictionary are present. 

In order for the example to work the `hash_behaviour` property in `ansible.cfg` must be set to `merge` rather than the default. 

This should be documented or the play should be adjusted to use core standard practise.

**Comment by woledzki** [comment]
@benwaine fixdd in https://github.com/ansible-city/gocd_server
